graasp/graasp-player

- .eslintrc
- package.json
- src/components/common/ItemHeader.js
- src/components/main/HeaderRightContent.js
- src/components/main/MainScreen.js
- src/config/constants.js
- src/utils/user.js
- yarn.lock
This PR adds the compose button in the top right corner + the current item name in the top left corner.
close #9
> feat: add compose view button

- .github/workflows/cypress.yml
- cypress.json
- cypress/support/commands.js
- cypress/support/index.js
- cypress/support/server.js
- package.json
- yarn.lock
> ci: run cypress tests in github actions

- README.md
- cypress.json
- cypress/integration/ws.spec.js
- package.json
- src/components/common/Item.js
- src/components/common/MainMenu.js
- src/config/queryClient.js
- yarn.lock
This PR implements #13 for real-time item children updates.
- Updates `graasp-query-client`
- Uses associated websocket hooks by adapting existing code
> #13 feat: add real-time updates for children recursively

- package.json
- src/components/common/Item.js
> fix: pass apihost to appItem

- package.json
- src/config/queryClient.js
- src/utils/user.js
- yarn.lock
> refactor: update query client package

- src/components/common/SideContent.js
> fix: hide button and pinned panel if no pinned items

- src/index.js
> refactor: add graasp-ui css

- package.json
- src/components/common/FolderButton.js
- src/config/constants.js
- src/utils/item.js
- yarn.lock
> refactor: improve folder button

- package.json
- src/config/constants.js
- src/env.json
- src/index.js
- yarn.lock
> feat: add google analytics

- src/components/common/Item.js
- yarn.lock
> feat: provide requestApiAccessToken to apps

- .github/workflows/cypress.yml
- cypress/fixtures/items.js
- cypress/fixtures/members.js
- cypress/fixtures/useCases/staticElectricity.js
- cypress/integration/chatbox.spec.js
- cypress/integration/hidden.spec.js
- cypress/integration/main.spec.js
- cypress/integration/pinned.spec.js
- cypress/integration/ws.spec.js
- cypress/plugins/index.js
- cypress/support/commands.js
- cypress/support/server.js
- package.json
- src/components/common/Chatbox.js
- src/components/common/Item.js
- src/components/common/Tree/CustomTreeItem.js
- src/components/main/Home.js
- src/utils/item.js
- yarn.lock
> refactor: fix public access, add tests

- src/components/common/Item.js
- yarn.lock
> refactor: update data to send to appItem

- src/components/common/Item.js
> feat: show folder description

- src/components/main/CookiesBanner.js
> refactor: set cookie banner domain

- cypress/fixtures/links.js
- cypress/support/integrationUtils.js
- package.json
- src/components/common/BuilderButton.js
- src/components/common/Item.js
- src/components/main/CookiesBanner.js
- src/config/constants.js
- yarn.lock
This PR sets the graasp-ui library version.
I've used graasp-sdk at some places.
close #143
> 143 graasp UI

- src/config/constants.js
- src/index.js
- src/utils/cookies.js
> refactor: use graasp sdk hasAcceptedCookies

- package.json
- src/components/common/Item.js
- src/enums/itemTypes.js
- yarn.lock
> feat: add etherpad view

- package.json
- yarn.lock
> feat: upgrade packages

- .github/workflows/cdelivery-s3-caller.yml
- .github/workflows/cdeployment-s3-caller.yml
- .github/workflows/cintegration-s3-caller.yml
- .github/workflows/cypress.yml
This PR adds the concurrency setting to the ci workflows.
closes #172
> ci: add concurency setting to cancel previous running workflows

- cypress/e2e/main.cy.js
- src/components/common/SideContent.js
This PR removes the builder button.
closes #197
> feat: remove builder button

- .eslintrc
- cypress.config.ts
- cypress/e2e/header.cy.ts
- cypress/e2e/main.cy.ts
- cypress/fixtures/items.ts
- cypress/fixtures/links.ts
- cypress/support/integrationUtils.ts
- package.json
- src/config/constants.ts
- src/modules/item/Item.tsx
- yarn.lock
This PR fixes the bug where the link button would be show even when the setting was set to `false`.
An accompagnying PR was created in sdk to narrow types and remove casting, see https://github.com/graasp/graasp-sdk/pull/150
> fix: link button is shown when setting is false

- cypress.config.ts
- cypress/e2e/apps.cy.ts
- cypress/fixtures/apps.ts
- cypress/fixtures/apps/app.html
- cypress/fixtures/apps/apps.ts
- cypress/support/commands.ts
- cypress/support/integrationUtils.ts
- cypress/support/server.ts
- package.json
- src/modules/item/Item.tsx
- yarn.lock
This PR fixes the issue where apps load forever.
> fix: apps loading forever

- src/config/constants.ts
- src/modules/item/ItemForbiddenScreen.tsx
- src/modules/userSwitch/UserSwitchWrapper.tsx
> feat: keep current window location on login of forbidden screen

- src/modules/header/HeaderNavigation.tsx
- src/modules/item/MainScreen.tsx
- src/modules/pages/ItemPage.tsx
The platform switch opens on click, it is closed by default.
fix #208
> feat(ui): responsive design improvements

- cypress/e2e/navigation.cy.ts
- cypress/fixtures/items.ts
- package.json
- src/utils/tree.ts
- yarn.lock
> fix: return all children for navigation

- package.json
- src/contexts/LayoutContext.tsx
- src/modules/header/HeaderNavigation.tsx
- src/modules/item/MainScreen.tsx
- yarn.lock
> fix: set pinned side content isopen default value to false

- .github/workflows/cypress.yml
- cypress/e2e/pinned.cy.ts
- cypress/fixtures/items.ts
- src/modules/rightPanel/SideContent.tsx
- vite.config.ts
> fix: filter hidden from pinned

- src/modules/item/Item.tsx
Remove the description above the content when it is a folder.
> feat: remove the description above the folder title

- cypress/support/utils.ts
- src/modules/item/NavigationButton.tsx
- src/modules/rightPanel/SideContent.tsx
- src/utils/item.ts
- src/utils/tree.ts
I removed the sorting for the tree since it's handled by the backend.
close #5
> refactor: remove some util

- cypress/e2e/redirections.cy.ts
- src/App.tsx
- src/config/selectors.ts
- src/modules/item/ItemForbiddenScreen.tsx
In this PR: 
- add home page url when redirecting to the signin page
> fix: add redirection url on home page authorization

- .github/workflows/build.yml
- .gitignore
- cypress/e2e/shuffle.cy.ts
- cypress/fixtures/items.ts
- package.json
- src/config/paths.ts
- src/config/selectors.ts
- src/modules/navigation/ItemNavigation.tsx
- src/modules/navigationIsland/PreviousNextButtons.tsx
- src/utils/shuffle.test.ts
- src/utils/shuffle.ts
- vite.config.ts
- yarn.lock
> feat: support shuffling children

- cypress/e2e/shuffle.cy.ts
- cypress/fixtures/items.ts
- src/utils/shuffle.test.ts
> fix: fix or remove tests that were failing

- src/modules/common/ItemCard.tsx
- src/modules/item/MainScreen.tsx
- src/modules/navigation/tree/TreeView.tsx
- src/modules/navigationIsland/PreviousNextButtons.tsx
> feat: call trigger view action on item page mounting

- src/modules/navigationIsland/CustomButtons.tsx
- src/modules/navigationIsland/NavigationIsland.tsx
- src/modules/navigationIsland/PreviousNextButtons.tsx
https://github.com/graasp/graasp-player/assets/39373170/3fe80bd7-5202-44a0-913a-65661b459ada
> Proposed changes for skeleton

- cypress/e2e/island.cy.ts
- cypress/fixtures/items.ts
- src/config/selectors.ts
- src/modules/item/Item.tsx
- src/modules/navigationIsland/NavigationIsland.tsx
> fix: duplicated island

- cypress/e2e/pinned.cy.ts
- cypress/fixtures/items.ts
- cypress/support/server.ts
- src/modules/item/Item.tsx
- src/modules/navigation/tree/LoadingTree.tsx
- src/modules/rightPanel/SideContent.tsx
> fix: pins should not be inherited
